import localFont from "next/font/local";
import "@/app/globals.css";
import MenuPrincipal from "@/components/menu-principal";


const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata = {
  title: "Información tutorial",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased h-screen flex leading-4`} >

       
          <MenuPrincipal />
       

        <main className="mx-2 pb-6 grow  overflow-y-auto">
          {children}
        </main>

      </body>
    </html>
  );
}
